# Generated by Django 5.2.6 on 2025-09-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
